DELETE FROM dbo.Sources;
DELETE FROM dbo.HarvestHistory;
DELETE FROM dbo.Params;
DELETE FROM dbo.Requests;
DELETE FROM dbo.MetadataNotifications;
DELETE FROM dbo.metadatanotifiers;
DELETE FROM dbo.MetadataRating;
DELETE FROM dbo.OperationAllowed where metadataid in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(metadataid in (SELECT id FROM dbo.METADATA)) OR NOT (groupid in ('-1','0','1'));
DELETE FROM dbo.metadatastatus where metadataid in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(metadataid in (SELECT id FROM dbo.METADATA));
DELETE FROM dbo.MetadataCateg where metadataid in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(metadataid in (SELECT id FROM dbo.METADATA));
DELETE FROM dbo.Validation where metadataid in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(metadataid in (SELECT id FROM dbo.METADATA));
DELETE FROM dbo.Workspace where id in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(id in (SELECT id FROM dbo.METADATA));
DELETE FROM dbo.Metadata where istemplate in ('n','s','y');
UPDATE dbo.Metadata set owner = '1';
DELETE FROM dbo.UserGroups where NOT (userId = '1');
DELETE FROM dbo.GroupsDes WHERE idDes not in ('-1','0','1') OR not (langid in ('dut','eng','fre','ger'));
DELETE FROM dbo.Groups WHERE id not in ('-1','0','1');
DELETE FROM dbo.categoriesdes WHERE langid not in ('dut','eng','fre','ger');
DELETE FROM dbo.cswservercapabilitiesinfo WHERE langid not in ('dut','eng','fre','ger');
DELETE FROM dbo.operationsdes WHERE langid not in ('dut','eng','fre','ger');
DELETE FROM dbo.Users WHERE id not in ('1');
DELETE FROM dbo.ValidationWorkspace where metadataid in (SELECT id FROM dbo.METADATA WHERE istemplate in ('n','s','y')) OR NOT(metadataid in (SELECT id FROM dbo.METADATA));
DELETE FROM dbo.Relations;
