INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Root','1');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Citizens','2');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV','3');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Publieke sector','4');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Private sector','5');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg','438');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('IS4U','805');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VITO','1024');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Training','1500');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis (Training)','1501');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet (Training)','1502');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax (Training)','1503');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn (Training)','1504');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom (Training)','1505');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ELIA (Training)','1506');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('PIDPA (Training)','1507');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VMW (Training)','1508');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link (Training)','1509');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV (Training)','1633');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV_Groen','1639');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV_Geel','1642');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV_Oranje','1645');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV_Rood','1648');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV_Test','1811');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link_Geel','1743');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link_Groen','1744');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link_Oranje','1745');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link_Rood','1746');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VMW_Geel','1739');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VMW_Groen','1740');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VMW_Oranje','1741');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VMW_Rood','1742');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('PIDPA_Geel','1728');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('PIDPA_Groen','1729');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('PIDPA_Oranje','1730');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('PIDPA_Rood','1731');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ELIA_Geel','1720');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ELIA_Groen','1721');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ELIA_Oranje','1722');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ELIA_Rood','1723');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom_Geel','1707');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom_Groen','1708');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom_Oranje','1709');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom_Rood','1710');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn_Geel','1711');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn_Groen','1712');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn_Oranje','1713');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn_Rood','1714');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax_Geel','1724');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax_Groen','1725');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax_Oranje','1726');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax_Rood','1727');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet_Geel','1735');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet_Groen','1736');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet_Oranje','1737');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet_Rood','1738');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis_Geel','1716');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis_Groen','1717');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis_Oranje','1718');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis_Rood','1719');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg HRM','446');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg ICT','455');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Blauw','654');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Rood','655');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Groen','842');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Paars','844');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Oranje','845');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Geel_kleur','1177');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg Productie','1208');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Geogroup','1411');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg','1805');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AutoUI Zwart','1917');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AutoUI Geel','1918');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('RVV','2041');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('KLIP DF','2499');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgPAV1','2500');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgPAV2','2503');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgPAV3','2513');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgKLB1','2514');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgKLB2','2517');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrgKLB3','2526');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg1','2527');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg2','2530');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg3','2539');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrgPAV1','2540');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrgPAV2','2543');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV3','2552');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrgKLB1','2553');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrgKLB2','2556');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrgKLB3','2565');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrg1','2566');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrg2','2569');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestOrg3','2578');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.1','2570');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.2','2571');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.3','2572');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.2.1','2573');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.2.2','2574');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.1.1','2575');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.1.2','2576');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg2.1.3','2577');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg1.1','2567');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrg1.2','2568');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.1','2557');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.2','2558');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.3','2559');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.2.1','2560');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.2.2','2561');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.1.1','2562');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.1.2','2563');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB2.1.3','2564');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB1.1','2554');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgKLB1.2','2555');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.1','2544');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.2','2545');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.3','2546');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.2.1','2547');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.2.2','2548');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.1.1','2549');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.1.2','2550');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV2.1.3','2551');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV1.1','2541');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SoapUITestSubOrgPAV1.2','2542');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.1','2531');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.2','2532');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.3','2533');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.2.1','2534');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.2.2','2535');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.1.1','2536');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.1.2','2537');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg2.1.3','2538');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg1.1','2528');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrg1.2','2529');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.1','2518');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.2','2519');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.3','2520');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.2.1','2524');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.2.2','2525');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.1.1','2521');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.1.2','2522');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB2.1.3','2523');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB1.1','2515');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgKLB1.2','2516');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.1','2504');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.2','2505');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.3','2506');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.2.1','2511');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.2.2','2512');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.1.1','2507');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.1.2','2509');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV2.1.3','2510');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV1.1','2501');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestSubOrgPAV1.2','2502');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVAalst','2042');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVBeernem','2043');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVDamme','2044');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVEdegem','2045');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVGavere','2046');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVHalle','2047');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVIeper','2048');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVJabbeke','2049');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVKalmthout','2050');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVLaakdal','2051');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVMaaseik','2052');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVNazareth','2053');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVOlen','2054');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVPeer','2055');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVRanst','2056');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVSchelle','2057');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVTemse','2058');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVVeurne','2059');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVWaarschoot','2060');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVZandhoven','2061');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVAvelgem','2062');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVBrugge','2063');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVDuffel','2064');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVEvergem','2065');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVGrobbendonk','2066');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVHulshout','2068');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVIzegem','2069');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVKoksijde','2070');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVLovendegem','2071');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVMol','2072');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVNinove','2073');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVOverpelt','2074');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVPuurs','2075');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVRuislede','2076');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestRVVStekene','2077');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SW','2338');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ontwerp & uitvoering publ.ruimte','2339');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ontwerp','2340');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('uitvoering','2341');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Databeheer','1412');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling GeoDiensten','1413');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling IT','1618');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Research','1871');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Testers','1897');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Niveau K','1948');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Entiteit Training','1869');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SubTestOrgProductie','1460');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Oker','1178');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Citroengeel','1179');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Paars_Sub1','1188');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Paars_Sub2','1189');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Paars_Sub3','1190');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SubOrganisatieGroen','1172');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Groen_Sub1','1192');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Groen_Sub2','1193');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Groen_Sub3','1194');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SubGroen1','1628');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SubGroen2','1629');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Groen_Sub1_1','1632');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SubOrganisatieGroen_Sub1','1755');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Organisatie Groen - SubOrganisatieGroen - SubOrganisatieGroen_Sub1 - Afdeling Sub 1_1','1808');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TestOrg ICT helpdesk','456');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis','16');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Arcadis Belgium','646');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom','647');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Capgemini','648');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Elia - powerlinks','649');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Fluxys','650');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Geovise','651');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('KPN Belgium nv','652');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Telenet','653');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Hewlett-Packard Belgium','856');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Akin bvba','1063');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Architectuur A. Spaas','1064');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Baert en zonen nv','1065');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Cocquyt A. bvba','1066');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('D+A consult nv','1067');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Vliegher BVBA','1068');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Fabricom - GDFSuez','1069');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gcs Infra bvba','1070');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Grontmij Vlaanderen nv','1071');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Imtech Belgium','1072');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Jacops nv','1074');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Kabelwerken Van Goethem - Theunis','1075');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Larabo bvba','1076');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Limburgse boringen nv','1077');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Logistics Trading & Consulting bvba','1078');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Maes Elektro nv','1079');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Algemene Ondernemingen Melotte nv','1080');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Molok West-Europe nv','1081');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Plantec nv','1082');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Wagro bvba','1083');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Wouters bvba','1084');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Scheldekabel nv','1085');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Studiebureau Dumoulin Jos bvba','1086');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Studiebureau Jouret bvba','1087');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('StudiebureauTalboom bvba','1088');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Studiegroep Irtas bvba','1089');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Torfs & Van den bergh nv','1090');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Van den berghe gebroeders nv','1091');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vanhoeyveld b&m bvba','1092');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vanhulle bvba','1093');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vecari nv','1094');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Verstraete nv','1095');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Verstraete-Verhulst bvba','1096');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Visser & Smit Hanab nv','1097');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Welec nv','1098');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Uniconnect nv','1099');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Waterwegen en Zeekanaal NV (TEST RVV)','1219');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Maatschappij van de Brugse Zeevaartinrichtingen (TEST RVV)','1220');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Autonoom gemeentebedrijf Haven Oostende - Regie communale Haven Oostende (TEST RVV)','1221');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Havenbedrijf Gent','1222');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeentelijk Havenbedrijf Antwerpen (TESTRVV)','1223');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Maatschappij voor het haven-, grond- en industrialisatiebeleid van het Linkerscheldeoevergebied (TEST RVV)','1224');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('M2Q','1285');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('CIPAL','1347');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Maatschappij Linkerscheldeoever','1675');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Maatschappij van de Brugse Zeevaartinrichtingen','1676');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Profit','1699');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('AGIV Aannemer','1900');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('HL Consulting','2173');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Geographic Information Management nv','1700');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('SIGGIS','1962');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Technum-Tractebel','2010');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Centrum voor Informatica','2039');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('4CGRID bvba','2130');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Aannemer Vandenplas','2137');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vision','2144');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('HEMMIS','2146');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Ventura (test)','2157');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Geo-IT BVBA','2184');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Merkator','2191');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('NET-IT','2193');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('RD Engineering','2211');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('INFRABEL NV','2226');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep','2329');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep Directie West-Vlaanderen','2330');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep Directie Limburg','2331');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep Directie Oost-Vlaanderen','2332');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep West-Vlaanderen Oost','2347');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Watergroep West-Vlaanderen Centrum','2348');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 1','2230');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 2','2235');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 2.1','2236');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 2.2','2237');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 1.1','2231');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 1.2','2232');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrabel Area 1.3','2233');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('M2Q suborganisatie','1325');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Nieuwe sub organisatie','1703');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('sub-sub-organisatie','1326');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('sub-sub-sub-organisatie','1327');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Fluxys Belgium(Pipelines)','2409');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Fluxys Belgium (FOOV)','2410');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom Area 1.1','2433');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom Area 1.2','2434');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom Area 2.1','2435');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom Area 2.2','2436');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgacom Area 3','2437');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Brugge-Middenkust','1419');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Schelde-Lieve','1420');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Ijzer-Mandel','1421');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Leie-Schelde','1422');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Antwerpen','1423');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Kempen','1424');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Schelde-Waas','1425');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Zenne-Dender','1426');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Leuven','1427');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Mechelen','1428');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis ICT Relatiebeheer','1429');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eandis Netbeleid - Meth.& Mat.-Netwerkrisico's','1430');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgische Federale overheid','53');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Europese overheid','54');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gewestelijke overheden','55');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaanderen','56');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Intergemeentelijk samenwerkingsverband','665');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Belgische niet-Federale overheid','2487');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Service Public de Wallonie','2488');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Antwerpse Waterwerken','644');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Aquafin nv','645');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('infrax','656');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Integan','657');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provinciale Intercommunale drinkwatermaatschappij van de Provincie Antwerpen','660');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW','661');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Maatschappij voor Watervoorziening - Hoofddirectie Brussel','662');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Interleuven','1105');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Coördinatiecommissie Integraal Waterbeleid (TEST RVV)','1225');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Sprokkels','1495');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VZW 3Wplus','1680');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('West-Vlaamse Intercommuncale','1733');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Sproeten','2196');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link - TMVW T-ONT','2452');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW T-ACC','2459');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW T-BLAUW','2466');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Aalst-Asse','2460');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Deinze-Oudenaarde-Ronse','2461');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Brugge-Kust','2462');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Gent','2463');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Centraal','2464');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Productie & Transport','2465');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Aalst-Asse','2453');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Deinze-Oudenaarde-Ronse','2454');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Brugge-Kust','2455');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Gent','2456');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Centraal','2457');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Water-Link – TMVW – Productie & Transport','2458');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW Asse','2387');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW Brugge','2388');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW Gent','2389');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW P&T','2390');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('TMVW Ronse','2391');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Lokale besturen','57');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap Wegen en Verkeer','642');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Vervoermaatschappij De Lijn','663');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Verkeerscentrum','664');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap Landbouw en Visserij','903');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Landmaatschappij (TEST RVV)','1214');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap voor Natuur en Bos (TEST RVV)','1215');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Departement Ruimtelijke Ordening, Woonbeleid en Onroerend Erfgoed (TEST RVV)','1216');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Maatschappij voor Sociaal Wonen','1218');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Departement Mobiliteit en Openbare Werken - Beleid Mobiliteit en Verkeersveiligheid','1226');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse overheid','1355');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Andere','1359');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse provincie','1479');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provinciebestuur','1480');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie Vlaams-Brabant','1481');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie Antwerpen','1667');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Intergemeentelijke samenwerkingsverbanden','1360');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Sociale Huisvestingsmaatschappij','1362');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Interlokale Vereniging Wooncentrum Meetjesland','1681');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Autonoom gemeentebedrijf Haven Oostende','1856');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Politiezones','1961');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Politiezone RIHO','1965');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Kantonale Bouwmaatschappij van Beringen voor Huisvesting','1363');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Heibloem CVBA','1656');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Mandel','1657');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De nieuwe haard CV','1658');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Eigen Haard is Goud Waard','1659');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gewestelijke maatschappij voor volkswoningen','1660');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gewestelijke Vennootschap Eigen Dak CVBA','1661');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Hasseltse Huisvestingsmaatschappij','1662');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Woonmaatschappij Ijzer en Zee','1669');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Woningent','1670');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('ABC bvba','1679');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gewestelijke Maatschappij voor Woningbouw cvba','1682');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gewestelijke Maatschappij voor Woningbouw','1683');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Ideale Woning','1790');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlashaard CVBA','1861');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('VENECO','1361');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('IGEAN dienstverlening','1663');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('IGEMO','1664');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('IGO','1665');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Interwaas','1666');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Woonwinkel West','1668');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Veneco²','1671');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('DIGIPOLIS','1767');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax','1980');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax Site Dilbeek','1981');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax Site Hasselt','1982');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax Site Hoboken','1983');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax Site Lubbeek','1984');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Infrax Site Torhout','1985');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap','1356');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('EVA Publiek','1357');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('IVA zonder rechtspersoonlijkheid','1651');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap voor Natuur en Bos','1652');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Milieumaatschappij','1673');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Agentschap Wonen-Vlaanderen','1754');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Scheepvaart NV','1358');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Vlaamse Landmaatschappij','1672');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Waterwegen en Zeekanaal NV','1734');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn West Vlaanderen','1267');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('De Lijn Oost Vlaanderen','1268');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Wegen en Verkeer Antwerpen','1622');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Wegen en Verkeer Limburg','1623');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Wegen en Verkeer Oost-Vlaanderen','1624');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Wegen en Verkeer Vlaams-Brabant','1625');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Wegen en Verkeer West-Vlaanderen','1626');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Afdeling Elektromechanica en Telematica','1627');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Gent','31');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Evergem','39');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wetteren','48');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zoersel','50');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Eeklo','51');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Aalst','58');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Aalter','59');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Aarschot','60');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Aartselaar','61');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Affligem','62');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Alken','63');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Alveringem','64');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Antwerpen','65');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Anzegem','66');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ardooie','67');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Arendonk','68');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente As','69');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Asse','70');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Assenede','71');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Avelgem','72');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Baarle-Hertog','73');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Balen','74');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Beernem','75');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Beerse','76');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Beersel','77');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Begijnendijk','78');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bekkevoort','79');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Beringen','80');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Berlaar','81');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Berlare','82');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bertem','83');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bever','84');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Beveren','85');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bierbeek','86');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Bilzen','87');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Blankenberge','88');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bocholt','89');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Boechout','90');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bonheiden','91');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Boom','92');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Boortmeerbeek','93');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Borgloon','94');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bornem','95');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Borsbeek','96');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Boutersem','97');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Brakel','98');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Brasschaat','99');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Brecht','100');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Bredene','101');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Bree','102');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Brugge','103');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Buggenhout','104');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Damme','105');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente De Haan','106');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente De Panne','107');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente De Pinte','108');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Deerlijk','109');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Deinze','110');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Denderleeuw','111');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Dendermonde','112');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Dentergem','113');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Dessel','114');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Destelbergen','115');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Diepenbeek','116');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Diest','117');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Diksmuide','118');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Dilbeek','119');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Dilsen-Stokkem','120');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Drogenbos','121');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Duffel','122');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Edegem','123');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Erpe-Mere','124');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Essen','125');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Galmaarden','126');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Gavere','127');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Geel','128');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Geetbets','129');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Genk','130');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Geraardsbergen','131');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Gingelom','132');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Gistel','133');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Glabbeek','134');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Gooik','135');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Grimbergen','136');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Grobbendonk','137');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Haacht','138');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Haaltert','139');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Halen','140');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Halle','141');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ham','142');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hamme','143');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Hamont-Achel','144');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Harelbeke','145');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Hasselt','146');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hechtel-Eksel','147');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Heers','148');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Heist-op-den-Berg','149');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hemiksem','150');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herent','151');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Herentals','152');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herenthout','153');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Herk-de-Stad','154');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herne','155');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herselt','156');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herstappe','157');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Herzele','158');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Heusden-Zolder','159');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Heuvelland','160');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hoegaarden','161');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hoeilaart','162');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hoeselt','163');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Holsbeek','164');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hooglede','165');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Hoogstraten','166');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Horebeke','167');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Houthalen-Helchteren','168');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Houthulst','169');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hove','170');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Huldenberg','171');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Hulshout','172');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ichtegem','173');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Ieper','174');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ingelmunster','175');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Izegem','176');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Jabbeke','177');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kalmthout','178');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kampenhout','179');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kapelle-op-den-Bos','180');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kapellen','181');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kaprijke','182');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kasterlee','183');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Keerbergen','184');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kinrooi','185');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kluisbergen','186');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Knesselare','187');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Knokke-Heist','188');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Koekelare','189');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Koksijde','190');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kontich','191');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kortemark','192');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kortenaken','193');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kortenberg','194');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kortessem','195');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Kortrijk','196');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kraainem','197');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kruibeke','198');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kruishoutem','199');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Kuurne','200');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Laakdal','201');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Laarne','202');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lanaken','203');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Landen','204');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Langemark-Poelkapelle','205');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lebbeke','206');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lede','207');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ledegem','208');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lendelede','209');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lennik','210');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Leopoldsburg','211');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Leuven','212');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lichtervelde','213');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Liedekerke','214');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Lier','215');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lierde','216');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lille','217');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Linkebeek','218');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lint','219');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Linter','220');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Lo-Reninge','221');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lochristi','222');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Lokeren','223');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Lommel','224');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Londerzeel','225');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lovendegem','226');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lubbeek','227');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Lummen','228');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Maarkedal','229');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Maaseik','230');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Maasmechelen','231');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Machelen','232');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Maldegem','233');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Malle','234');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Mechelen','235');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Meerhout','236');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Meeuwen-Gruitrode','237');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Meise','238');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Melle','239');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Menen','240');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Merchtem','241');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Merelbeke','242');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Merksplas','243');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Mesen','244');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Meulebeke','245');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Middelkerke','246');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Moerbeke','247');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Mol','248');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Moorslede','249');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Mortsel','250');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Nazareth','251');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Neerpelt','252');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Nevele','253');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Niel','254');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Nieuwerkerken','255');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Nieuwpoort','256');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Nijlen','257');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Ninove','258');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Olen','259');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Oostende','260');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Oosterzele','261');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Oostkamp','262');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Oostrozebeke','263');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Opglabbeek','264');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Opwijk','265');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Oud-Heverlee','266');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Oud-Turnhout','267');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Oudenaarde','268');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Oudenburg','269');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Overijse','270');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Overpelt','271');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Peer','272');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Pepingen','273');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Pittem','274');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Poperinge','275');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Putte','276');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Puurs','277');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ranst','278');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ravels','279');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Retie','280');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Riemst','281');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Rijkevorsel','282');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Roeselare','283');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Ronse','284');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Roosdaal','285');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Rotselaar','286');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ruiselede','287');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Rumst','288');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Schelle','289');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Scherpenheuvel-Zichem','290');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Schilde','291');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Schoten','292');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Amands','293');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Genesius-Rode','294');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Gillis-Waas','295');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Katelijne-Waver','296');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Laureins','297');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Lievens-Houtem','298');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Martens-Latem','299');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Sint-Niklaas','300');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Sint-Pieters-Leeuw','301');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Sint-Truiden','302');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Spiere-Helkijn','303');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Stabroek','304');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Staden','305');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Steenokkerzeel','306');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Stekene','307');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Temse','308');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Ternat','309');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Tervuren','310');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Tessenderlo','311');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Tielt','312');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Tielt-Winge','313');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Tienen','314');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Tongeren','315');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Torhout','316');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Tremelo','317');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Turnhout','318');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Veurne','319');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Vilvoorde','320');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Vleteren','321');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Voeren','322');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Vorselaar','323');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Vosselaar','324');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Waarschoot','325');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Waasmunster','326');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wachtebeke','327');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Waregem','328');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wellen','329');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wemmel','330');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Wervik','331');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Westerlo','332');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wevelgem','333');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wezembeek-Oppem','334');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wichelen','335');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wielsbeke','336');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wijnegem','337');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Willebroek','338');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wingene','339');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wommelgem','340');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wortegem-Petegem','341');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Wuustwezel','342');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zandhoven','343');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zaventem','344');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zedelgem','345');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zele','346');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zelzate','347');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zemst','348');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zingem','349');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zomergem','350');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zonhoven','351');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zonnebeke','352');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Zottegem','353');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Stad Zoutleeuw','354');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zuienkerke','355');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zulte','356');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zutendaal','357');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zwalm','358');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zwevegem','359');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Zwijndrecht','360');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Herenthout','1850');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Zoutleeuw','1695');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Zaventem','1694');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Wortegem-Petegem','1693');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Wichelen','1692');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Westerlo','1691');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Wervik','1690');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Tervuren','1689');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Schilde','1688');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Ronse - Technische Dienst','1494');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Rijkevorsel','1687');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Mortsel','1686');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Kruibeke','1685');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Kalmthout','1836');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Buggenhout','1864');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeentelijk Havenbedrijf Antwerpen','908');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Aalter','1684');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie Oost-Vlaanderen','507');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie West-Vlaanderen (TEST RVV)','1217');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie Limburg','1451');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Provincie West-Vlaanderen','1732');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Mobiliteit','2247');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Onderwijs','2249');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Bpost','2040');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Applications','900');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Gemeente Loes','1750');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Security','1880');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Security WVL','1881');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('Security OVL','1882');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('OCMW Loes','1752');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('MobileMapping','901');
