INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9959','Aeolus');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('5377','Agentschap Ondernemen - Antwerpen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('833','Agentschap Onroerend Erfgoed');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('838','Agentschap voor Maritieme Dienstverlening en Kust - Kust');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('839','Agentschap voor Natuur en Bos');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('3','AGIV');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('8579','Antea Group');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('868','Aquafin nv');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('794','Aquaterra nv');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9966','Coördinatiecommissie Integraal Waterbeleid');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('811','Departement Leefmilieu, Natuur en Energie - Land en Bodembescherming, Ondergrond, Natuurlijke Rijkdommen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('830','Departement Ruimte Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9960','Electronic Data Systems - Belgium');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9961','ESRI BELUX');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('174','Gemeente Kuurne');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('67','Gemeente Lille');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('37','Gemeente Zandhoven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('853','Instituut voor Natuur- en Bosonderzoek');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9963','Koninklijke Sterrenwacht van België');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('6304','KU Leuven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9086','Nationaal Geografisch Instituut');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('','Onbekend');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('858','Openbare Vlaamse Afvalstoffenmaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('799','Provincie Limburg');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('800','Provincie Oost-Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1290','Provincie West-Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9964','Regionaal Landschap Noord-Hageland');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('9965','SCHOUKENS');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('242','Stad Gent');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('134','Stad Leuven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('176','Stad Menen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('258','Stad Oudenaarde');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('6683','Universiteit Antwerpen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('5971','Universiteit Gent');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('871','Vlaamse Instelling voor Technologisch Onderzoek');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('872','Vlaamse Landmaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('860','Vlaamse Maatschappij voor Sociaal Wonen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('861','Vlaamse Milieumaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('877','Waterwegen en Zeekanaal NV');
