INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2853','Aeolus');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2727','Agentschap Ondernemen - Antwerpen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2867','Agentschap Onroerend Erfgoed');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2862','Agentschap voor Maritieme Dienstverlening en Kust - Kust');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1652','Agentschap voor Natuur en Bos');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('3','AGIV');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2869','Antea Group');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('645','Aquafin nv');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2854','Aquaterra nv');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2855','Coördinatiecommissie Integraal Waterbeleid');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2730','Departement Leefmilieu, Natuur en Energie - Land en Bodembescherming, Ondergrond, Natuurlijke Rijkdommen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2873','Departement Ruimte Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2856','Electronic Data Systems - Belgium');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2857','ESRI BELUX');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('200','Gemeente Kuurne');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('217','Gemeente Lille');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('343','Gemeente Zandhoven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2858','Instituut voor Natuur- en Bosonderzoek');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2861','Koninklijke Sterrenwacht van België');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2860','KU Leuven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2863','Nationaal Geografisch Instituut');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('','Onbekend');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2864','Openbare Vlaamse Afvalstoffenmaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1451','Provincie Limburg');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('507','Provincie Oost-Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1732','Provincie West-Vlaanderen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2866','Regionaal Landschap Noord-Hageland');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2868','SCHOUKENS');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('31','Stad Gent');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('212','Stad Leuven');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('240','Stad Menen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('268','Stad Oudenaarde');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2871','Universiteit Antwerpen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2870','Universiteit Gent');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('2872','Vlaamse Instelling voor Technologisch Onderzoek');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1672','Vlaamse Landmaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1218','Vlaamse Maatschappij voor Sociaal Wonen');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1673','Vlaamse Milieumaatschappij');
INSERT INTO dbo.GroupsToCreate (name, description) VALUES('1734','Waterwegen en Zeekanaal NV');
